server:
  port: 8090
  context-path: /pugna
  max-http-header-size: 88192
spring:
  datasource:
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    url:  jdbc:mysql://192.168.199.112:3306/pugna?Unicode=true&autoReconnect=true&characterEncoding=UTF-8
  redis:
    host: localhost
    port: 6379
steam:
  key: 8CD1268BDB73A449446863EEC2DE17D0
dota2:
  heros:
    image_url: http://cdn.dota2.com/apps/dota2/images/heroes/




mybatis:
  configLocation: classpath:mybatis-config.xml
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.cc.entity

